export const subjectsList: string[] = [
  "LOADER_NOT_FINISHED",
  "WRONG_DATA",
  "VISUALIZATION_ERROR",
  "CANT_FIND_DATA",
  "LONG_WAITING",
  "CANT_UNDERSTAND_REPORT",
  "NOT_UNDERSTAND_HOW_SERVICE_WORKS",
  "WANT_CHANGE_FILTERS",
  "OTHER"
];